-- Copyright (c) 2026 WSO2 LLC. (https://www.wso2.com).
--
-- WSO2 LLC. licenses this file to you under the Apache License,
-- Version 2.0 (the "License"); you may not use this file except
-- in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the License for the
-- specific language governing permissions and limitations
-- under the License.

-- Server-side attendee search (Phase D) pages with keyset pagination ordered by
-- (created_at, id). Name/company/title are AES-GCM encrypted at rest, so they
-- cannot be ORDER BY'd or ILIKE-filtered in SQL -- that text filtering happens
-- in Go after decryption (same constraint speakers hit in Phase B). The only
-- SQL-usable stable, total ordering is the plaintext (created_at, id); this
-- composite index backs the keyset seek so paging stays bounded as the table
-- grows. id alone is the PK (already indexed) but ordering by registration time
-- with an id tiebreak is the meaningful, deterministic order we page by.
-- attendees is an owned table (migration 003), so this index is ours to add.
CREATE INDEX attendees_created_at_id_idx ON attendees (created_at, id);
